// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClientServer.proto

package cssort.protocol;

public final class ClientServerProtocol {
  private ClientServerProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ClientToServerArrayOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cssort.ClientToServerArray)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated int32 data = 1;</code>
     */
    java.util.List<java.lang.Integer> getDataList();
    /**
     * <code>repeated int32 data = 1;</code>
     */
    int getDataCount();
    /**
     * <code>repeated int32 data = 1;</code>
     */
    int getData(int index);
  }
  /**
   * Protobuf type {@code cssort.ClientToServerArray}
   */
  public static final class ClientToServerArray extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:cssort.ClientToServerArray)
      ClientToServerArrayOrBuilder {
    // Use ClientToServerArray.newBuilder() to construct.
    private ClientToServerArray(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ClientToServerArray(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ClientToServerArray defaultInstance;
    public static ClientToServerArray getDefaultInstance() {
      return defaultInstance;
    }

    public ClientToServerArray getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ClientToServerArray(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                data_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              data_.add(input.readInt32());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
                data_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                data_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          data_ = java.util.Collections.unmodifiableList(data_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cssort.protocol.ClientServerProtocol.internal_static_cssort_ClientToServerArray_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cssort.protocol.ClientServerProtocol.internal_static_cssort_ClientToServerArray_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cssort.protocol.ClientServerProtocol.ClientToServerArray.class, cssort.protocol.ClientServerProtocol.ClientToServerArray.Builder.class);
    }

    public static com.google.protobuf.Parser<ClientToServerArray> PARSER =
        new com.google.protobuf.AbstractParser<ClientToServerArray>() {
      public ClientToServerArray parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ClientToServerArray(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ClientToServerArray> getParserForType() {
      return PARSER;
    }

    public static final int DATA_FIELD_NUMBER = 1;
    private java.util.List<java.lang.Integer> data_;
    /**
     * <code>repeated int32 data = 1;</code>
     */
    public java.util.List<java.lang.Integer>
        getDataList() {
      return data_;
    }
    /**
     * <code>repeated int32 data = 1;</code>
     */
    public int getDataCount() {
      return data_.size();
    }
    /**
     * <code>repeated int32 data = 1;</code>
     */
    public int getData(int index) {
      return data_.get(index);
    }

    private void initFields() {
      data_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < data_.size(); i++) {
        output.writeInt32(1, data_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < data_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(data_.get(i));
        }
        size += dataSize;
        size += 1 * getDataList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static cssort.protocol.ClientServerProtocol.ClientToServerArray parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cssort.protocol.ClientServerProtocol.ClientToServerArray parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cssort.protocol.ClientServerProtocol.ClientToServerArray parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cssort.protocol.ClientServerProtocol.ClientToServerArray parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cssort.protocol.ClientServerProtocol.ClientToServerArray parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cssort.protocol.ClientServerProtocol.ClientToServerArray parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static cssort.protocol.ClientServerProtocol.ClientToServerArray parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static cssort.protocol.ClientServerProtocol.ClientToServerArray parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static cssort.protocol.ClientServerProtocol.ClientToServerArray parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cssort.protocol.ClientServerProtocol.ClientToServerArray parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(cssort.protocol.ClientServerProtocol.ClientToServerArray prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cssort.ClientToServerArray}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cssort.ClientToServerArray)
        cssort.protocol.ClientServerProtocol.ClientToServerArrayOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cssort.protocol.ClientServerProtocol.internal_static_cssort_ClientToServerArray_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cssort.protocol.ClientServerProtocol.internal_static_cssort_ClientToServerArray_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cssort.protocol.ClientServerProtocol.ClientToServerArray.class, cssort.protocol.ClientServerProtocol.ClientToServerArray.Builder.class);
      }

      // Construct using cssort.protocol.ClientServerProtocol.ClientToServerArray.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        data_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cssort.protocol.ClientServerProtocol.internal_static_cssort_ClientToServerArray_descriptor;
      }

      public cssort.protocol.ClientServerProtocol.ClientToServerArray getDefaultInstanceForType() {
        return cssort.protocol.ClientServerProtocol.ClientToServerArray.getDefaultInstance();
      }

      public cssort.protocol.ClientServerProtocol.ClientToServerArray build() {
        cssort.protocol.ClientServerProtocol.ClientToServerArray result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cssort.protocol.ClientServerProtocol.ClientToServerArray buildPartial() {
        cssort.protocol.ClientServerProtocol.ClientToServerArray result = new cssort.protocol.ClientServerProtocol.ClientToServerArray(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          data_ = java.util.Collections.unmodifiableList(data_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.data_ = data_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cssort.protocol.ClientServerProtocol.ClientToServerArray) {
          return mergeFrom((cssort.protocol.ClientServerProtocol.ClientToServerArray)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cssort.protocol.ClientServerProtocol.ClientToServerArray other) {
        if (other == cssort.protocol.ClientServerProtocol.ClientToServerArray.getDefaultInstance()) return this;
        if (!other.data_.isEmpty()) {
          if (data_.isEmpty()) {
            data_ = other.data_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureDataIsMutable();
            data_.addAll(other.data_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cssort.protocol.ClientServerProtocol.ClientToServerArray parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cssort.protocol.ClientServerProtocol.ClientToServerArray) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<java.lang.Integer> data_ = java.util.Collections.emptyList();
      private void ensureDataIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          data_ = new java.util.ArrayList<java.lang.Integer>(data_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated int32 data = 1;</code>
       */
      public java.util.List<java.lang.Integer>
          getDataList() {
        return java.util.Collections.unmodifiableList(data_);
      }
      /**
       * <code>repeated int32 data = 1;</code>
       */
      public int getDataCount() {
        return data_.size();
      }
      /**
       * <code>repeated int32 data = 1;</code>
       */
      public int getData(int index) {
        return data_.get(index);
      }
      /**
       * <code>repeated int32 data = 1;</code>
       */
      public Builder setData(
          int index, int value) {
        ensureDataIsMutable();
        data_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 data = 1;</code>
       */
      public Builder addData(int value) {
        ensureDataIsMutable();
        data_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 data = 1;</code>
       */
      public Builder addAllData(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureDataIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, data_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 data = 1;</code>
       */
      public Builder clearData() {
        data_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:cssort.ClientToServerArray)
    }

    static {
      defaultInstance = new ClientToServerArray(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:cssort.ClientToServerArray)
  }

  public interface ServerToClientArrayOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cssort.ServerToClientArray)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated int32 data = 1;</code>
     */
    java.util.List<java.lang.Integer> getDataList();
    /**
     * <code>repeated int32 data = 1;</code>
     */
    int getDataCount();
    /**
     * <code>repeated int32 data = 1;</code>
     */
    int getData(int index);

    /**
     * <code>required int64 requestTime = 2;</code>
     */
    boolean hasRequestTime();
    /**
     * <code>required int64 requestTime = 2;</code>
     */
    long getRequestTime();

    /**
     * <code>required int64 processTime = 3;</code>
     */
    boolean hasProcessTime();
    /**
     * <code>required int64 processTime = 3;</code>
     */
    long getProcessTime();
  }
  /**
   * Protobuf type {@code cssort.ServerToClientArray}
   */
  public static final class ServerToClientArray extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:cssort.ServerToClientArray)
      ServerToClientArrayOrBuilder {
    // Use ServerToClientArray.newBuilder() to construct.
    private ServerToClientArray(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ServerToClientArray(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ServerToClientArray defaultInstance;
    public static ServerToClientArray getDefaultInstance() {
      return defaultInstance;
    }

    public ServerToClientArray getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ServerToClientArray(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                data_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              data_.add(input.readInt32());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
                data_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                data_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 16: {
              bitField0_ |= 0x00000001;
              requestTime_ = input.readInt64();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000002;
              processTime_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          data_ = java.util.Collections.unmodifiableList(data_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cssort.protocol.ClientServerProtocol.internal_static_cssort_ServerToClientArray_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cssort.protocol.ClientServerProtocol.internal_static_cssort_ServerToClientArray_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cssort.protocol.ClientServerProtocol.ServerToClientArray.class, cssort.protocol.ClientServerProtocol.ServerToClientArray.Builder.class);
    }

    public static com.google.protobuf.Parser<ServerToClientArray> PARSER =
        new com.google.protobuf.AbstractParser<ServerToClientArray>() {
      public ServerToClientArray parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ServerToClientArray(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ServerToClientArray> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int DATA_FIELD_NUMBER = 1;
    private java.util.List<java.lang.Integer> data_;
    /**
     * <code>repeated int32 data = 1;</code>
     */
    public java.util.List<java.lang.Integer>
        getDataList() {
      return data_;
    }
    /**
     * <code>repeated int32 data = 1;</code>
     */
    public int getDataCount() {
      return data_.size();
    }
    /**
     * <code>repeated int32 data = 1;</code>
     */
    public int getData(int index) {
      return data_.get(index);
    }

    public static final int REQUESTTIME_FIELD_NUMBER = 2;
    private long requestTime_;
    /**
     * <code>required int64 requestTime = 2;</code>
     */
    public boolean hasRequestTime() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 requestTime = 2;</code>
     */
    public long getRequestTime() {
      return requestTime_;
    }

    public static final int PROCESSTIME_FIELD_NUMBER = 3;
    private long processTime_;
    /**
     * <code>required int64 processTime = 3;</code>
     */
    public boolean hasProcessTime() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 processTime = 3;</code>
     */
    public long getProcessTime() {
      return processTime_;
    }

    private void initFields() {
      data_ = java.util.Collections.emptyList();
      requestTime_ = 0L;
      processTime_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasRequestTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasProcessTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < data_.size(); i++) {
        output.writeInt32(1, data_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(2, requestTime_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(3, processTime_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < data_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(data_.get(i));
        }
        size += dataSize;
        size += 1 * getDataList().size();
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, requestTime_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, processTime_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static cssort.protocol.ClientServerProtocol.ServerToClientArray parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cssort.protocol.ClientServerProtocol.ServerToClientArray parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cssort.protocol.ClientServerProtocol.ServerToClientArray parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cssort.protocol.ClientServerProtocol.ServerToClientArray parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cssort.protocol.ClientServerProtocol.ServerToClientArray parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cssort.protocol.ClientServerProtocol.ServerToClientArray parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static cssort.protocol.ClientServerProtocol.ServerToClientArray parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static cssort.protocol.ClientServerProtocol.ServerToClientArray parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static cssort.protocol.ClientServerProtocol.ServerToClientArray parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cssort.protocol.ClientServerProtocol.ServerToClientArray parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(cssort.protocol.ClientServerProtocol.ServerToClientArray prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cssort.ServerToClientArray}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cssort.ServerToClientArray)
        cssort.protocol.ClientServerProtocol.ServerToClientArrayOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cssort.protocol.ClientServerProtocol.internal_static_cssort_ServerToClientArray_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cssort.protocol.ClientServerProtocol.internal_static_cssort_ServerToClientArray_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cssort.protocol.ClientServerProtocol.ServerToClientArray.class, cssort.protocol.ClientServerProtocol.ServerToClientArray.Builder.class);
      }

      // Construct using cssort.protocol.ClientServerProtocol.ServerToClientArray.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        data_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        requestTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        processTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cssort.protocol.ClientServerProtocol.internal_static_cssort_ServerToClientArray_descriptor;
      }

      public cssort.protocol.ClientServerProtocol.ServerToClientArray getDefaultInstanceForType() {
        return cssort.protocol.ClientServerProtocol.ServerToClientArray.getDefaultInstance();
      }

      public cssort.protocol.ClientServerProtocol.ServerToClientArray build() {
        cssort.protocol.ClientServerProtocol.ServerToClientArray result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cssort.protocol.ClientServerProtocol.ServerToClientArray buildPartial() {
        cssort.protocol.ClientServerProtocol.ServerToClientArray result = new cssort.protocol.ClientServerProtocol.ServerToClientArray(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          data_ = java.util.Collections.unmodifiableList(data_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.data_ = data_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000001;
        }
        result.requestTime_ = requestTime_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000002;
        }
        result.processTime_ = processTime_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cssort.protocol.ClientServerProtocol.ServerToClientArray) {
          return mergeFrom((cssort.protocol.ClientServerProtocol.ServerToClientArray)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cssort.protocol.ClientServerProtocol.ServerToClientArray other) {
        if (other == cssort.protocol.ClientServerProtocol.ServerToClientArray.getDefaultInstance()) return this;
        if (!other.data_.isEmpty()) {
          if (data_.isEmpty()) {
            data_ = other.data_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureDataIsMutable();
            data_.addAll(other.data_);
          }
          onChanged();
        }
        if (other.hasRequestTime()) {
          setRequestTime(other.getRequestTime());
        }
        if (other.hasProcessTime()) {
          setProcessTime(other.getProcessTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasRequestTime()) {
          
          return false;
        }
        if (!hasProcessTime()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cssort.protocol.ClientServerProtocol.ServerToClientArray parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cssort.protocol.ClientServerProtocol.ServerToClientArray) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<java.lang.Integer> data_ = java.util.Collections.emptyList();
      private void ensureDataIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          data_ = new java.util.ArrayList<java.lang.Integer>(data_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated int32 data = 1;</code>
       */
      public java.util.List<java.lang.Integer>
          getDataList() {
        return java.util.Collections.unmodifiableList(data_);
      }
      /**
       * <code>repeated int32 data = 1;</code>
       */
      public int getDataCount() {
        return data_.size();
      }
      /**
       * <code>repeated int32 data = 1;</code>
       */
      public int getData(int index) {
        return data_.get(index);
      }
      /**
       * <code>repeated int32 data = 1;</code>
       */
      public Builder setData(
          int index, int value) {
        ensureDataIsMutable();
        data_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 data = 1;</code>
       */
      public Builder addData(int value) {
        ensureDataIsMutable();
        data_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 data = 1;</code>
       */
      public Builder addAllData(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureDataIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, data_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 data = 1;</code>
       */
      public Builder clearData() {
        data_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      private long requestTime_ ;
      /**
       * <code>required int64 requestTime = 2;</code>
       */
      public boolean hasRequestTime() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 requestTime = 2;</code>
       */
      public long getRequestTime() {
        return requestTime_;
      }
      /**
       * <code>required int64 requestTime = 2;</code>
       */
      public Builder setRequestTime(long value) {
        bitField0_ |= 0x00000002;
        requestTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 requestTime = 2;</code>
       */
      public Builder clearRequestTime() {
        bitField0_ = (bitField0_ & ~0x00000002);
        requestTime_ = 0L;
        onChanged();
        return this;
      }

      private long processTime_ ;
      /**
       * <code>required int64 processTime = 3;</code>
       */
      public boolean hasProcessTime() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int64 processTime = 3;</code>
       */
      public long getProcessTime() {
        return processTime_;
      }
      /**
       * <code>required int64 processTime = 3;</code>
       */
      public Builder setProcessTime(long value) {
        bitField0_ |= 0x00000004;
        processTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 processTime = 3;</code>
       */
      public Builder clearProcessTime() {
        bitField0_ = (bitField0_ & ~0x00000004);
        processTime_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:cssort.ServerToClientArray)
    }

    static {
      defaultInstance = new ServerToClientArray(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:cssort.ServerToClientArray)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cssort_ClientToServerArray_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cssort_ClientToServerArray_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cssort_ServerToClientArray_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cssort_ServerToClientArray_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022ClientServer.proto\022\006cssort\"#\n\023ClientTo" +
      "ServerArray\022\014\n\004data\030\001 \003(\005\"M\n\023ServerToCli" +
      "entArray\022\014\n\004data\030\001 \003(\005\022\023\n\013requestTime\030\002 " +
      "\002(\003\022\023\n\013processTime\030\003 \002(\003B\'\n\017cssort.proto" +
      "colB\024ClientServerProtocol"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_cssort_ClientToServerArray_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cssort_ClientToServerArray_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_cssort_ClientToServerArray_descriptor,
        new java.lang.String[] { "Data", });
    internal_static_cssort_ServerToClientArray_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_cssort_ServerToClientArray_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_cssort_ServerToClientArray_descriptor,
        new java.lang.String[] { "Data", "RequestTime", "ProcessTime", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
