// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProfilerClientProtocol.proto

package cssort.protocol;

public final class ProfilerClientProtocol {
  private ProfilerClientProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ProfilerToClientInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cssort.ProfilerToClientInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 N = 1;</code>
     */
    boolean hasN();
    /**
     * <code>required int32 N = 1;</code>
     */
    int getN();

    /**
     * <code>required int32 delta = 2;</code>
     */
    boolean hasDelta();
    /**
     * <code>required int32 delta = 2;</code>
     */
    int getDelta();

    /**
     * <code>required int32 X = 3;</code>
     */
    boolean hasX();
    /**
     * <code>required int32 X = 3;</code>
     */
    int getX();

    /**
     * <code>required int32 arch = 4;</code>
     */
    boolean hasArch();
    /**
     * <code>required int32 arch = 4;</code>
     */
    int getArch();
  }
  /**
   * Protobuf type {@code cssort.ProfilerToClientInfo}
   */
  public static final class ProfilerToClientInfo extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:cssort.ProfilerToClientInfo)
      ProfilerToClientInfoOrBuilder {
    // Use ProfilerToClientInfo.newBuilder() to construct.
    private ProfilerToClientInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ProfilerToClientInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ProfilerToClientInfo defaultInstance;
    public static ProfilerToClientInfo getDefaultInstance() {
      return defaultInstance;
    }

    public ProfilerToClientInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ProfilerToClientInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              n_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              delta_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              x_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              arch_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cssort.protocol.ProfilerClientProtocol.internal_static_cssort_ProfilerToClientInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cssort.protocol.ProfilerClientProtocol.internal_static_cssort_ProfilerToClientInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cssort.protocol.ProfilerClientProtocol.ProfilerToClientInfo.class, cssort.protocol.ProfilerClientProtocol.ProfilerToClientInfo.Builder.class);
    }

    public static com.google.protobuf.Parser<ProfilerToClientInfo> PARSER =
        new com.google.protobuf.AbstractParser<ProfilerToClientInfo>() {
      public ProfilerToClientInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ProfilerToClientInfo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ProfilerToClientInfo> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int N_FIELD_NUMBER = 1;
    private int n_;
    /**
     * <code>required int32 N = 1;</code>
     */
    public boolean hasN() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 N = 1;</code>
     */
    public int getN() {
      return n_;
    }

    public static final int DELTA_FIELD_NUMBER = 2;
    private int delta_;
    /**
     * <code>required int32 delta = 2;</code>
     */
    public boolean hasDelta() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 delta = 2;</code>
     */
    public int getDelta() {
      return delta_;
    }

    public static final int X_FIELD_NUMBER = 3;
    private int x_;
    /**
     * <code>required int32 X = 3;</code>
     */
    public boolean hasX() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 X = 3;</code>
     */
    public int getX() {
      return x_;
    }

    public static final int ARCH_FIELD_NUMBER = 4;
    private int arch_;
    /**
     * <code>required int32 arch = 4;</code>
     */
    public boolean hasArch() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 arch = 4;</code>
     */
    public int getArch() {
      return arch_;
    }

    private void initFields() {
      n_ = 0;
      delta_ = 0;
      x_ = 0;
      arch_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasN()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDelta()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasX()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasArch()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, n_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, delta_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, x_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, arch_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, n_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, delta_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, x_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, arch_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static cssort.protocol.ProfilerClientProtocol.ProfilerToClientInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cssort.protocol.ProfilerClientProtocol.ProfilerToClientInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cssort.protocol.ProfilerClientProtocol.ProfilerToClientInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cssort.protocol.ProfilerClientProtocol.ProfilerToClientInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cssort.protocol.ProfilerClientProtocol.ProfilerToClientInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cssort.protocol.ProfilerClientProtocol.ProfilerToClientInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static cssort.protocol.ProfilerClientProtocol.ProfilerToClientInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static cssort.protocol.ProfilerClientProtocol.ProfilerToClientInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static cssort.protocol.ProfilerClientProtocol.ProfilerToClientInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cssort.protocol.ProfilerClientProtocol.ProfilerToClientInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(cssort.protocol.ProfilerClientProtocol.ProfilerToClientInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cssort.ProfilerToClientInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cssort.ProfilerToClientInfo)
        cssort.protocol.ProfilerClientProtocol.ProfilerToClientInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cssort.protocol.ProfilerClientProtocol.internal_static_cssort_ProfilerToClientInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cssort.protocol.ProfilerClientProtocol.internal_static_cssort_ProfilerToClientInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cssort.protocol.ProfilerClientProtocol.ProfilerToClientInfo.class, cssort.protocol.ProfilerClientProtocol.ProfilerToClientInfo.Builder.class);
      }

      // Construct using cssort.protocol.ProfilerClientProtocol.ProfilerToClientInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        n_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        delta_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        x_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        arch_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cssort.protocol.ProfilerClientProtocol.internal_static_cssort_ProfilerToClientInfo_descriptor;
      }

      public cssort.protocol.ProfilerClientProtocol.ProfilerToClientInfo getDefaultInstanceForType() {
        return cssort.protocol.ProfilerClientProtocol.ProfilerToClientInfo.getDefaultInstance();
      }

      public cssort.protocol.ProfilerClientProtocol.ProfilerToClientInfo build() {
        cssort.protocol.ProfilerClientProtocol.ProfilerToClientInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cssort.protocol.ProfilerClientProtocol.ProfilerToClientInfo buildPartial() {
        cssort.protocol.ProfilerClientProtocol.ProfilerToClientInfo result = new cssort.protocol.ProfilerClientProtocol.ProfilerToClientInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.n_ = n_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.delta_ = delta_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.x_ = x_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.arch_ = arch_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cssort.protocol.ProfilerClientProtocol.ProfilerToClientInfo) {
          return mergeFrom((cssort.protocol.ProfilerClientProtocol.ProfilerToClientInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cssort.protocol.ProfilerClientProtocol.ProfilerToClientInfo other) {
        if (other == cssort.protocol.ProfilerClientProtocol.ProfilerToClientInfo.getDefaultInstance()) return this;
        if (other.hasN()) {
          setN(other.getN());
        }
        if (other.hasDelta()) {
          setDelta(other.getDelta());
        }
        if (other.hasX()) {
          setX(other.getX());
        }
        if (other.hasArch()) {
          setArch(other.getArch());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasN()) {
          
          return false;
        }
        if (!hasDelta()) {
          
          return false;
        }
        if (!hasX()) {
          
          return false;
        }
        if (!hasArch()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cssort.protocol.ProfilerClientProtocol.ProfilerToClientInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cssort.protocol.ProfilerClientProtocol.ProfilerToClientInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int n_ ;
      /**
       * <code>required int32 N = 1;</code>
       */
      public boolean hasN() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 N = 1;</code>
       */
      public int getN() {
        return n_;
      }
      /**
       * <code>required int32 N = 1;</code>
       */
      public Builder setN(int value) {
        bitField0_ |= 0x00000001;
        n_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 N = 1;</code>
       */
      public Builder clearN() {
        bitField0_ = (bitField0_ & ~0x00000001);
        n_ = 0;
        onChanged();
        return this;
      }

      private int delta_ ;
      /**
       * <code>required int32 delta = 2;</code>
       */
      public boolean hasDelta() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 delta = 2;</code>
       */
      public int getDelta() {
        return delta_;
      }
      /**
       * <code>required int32 delta = 2;</code>
       */
      public Builder setDelta(int value) {
        bitField0_ |= 0x00000002;
        delta_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 delta = 2;</code>
       */
      public Builder clearDelta() {
        bitField0_ = (bitField0_ & ~0x00000002);
        delta_ = 0;
        onChanged();
        return this;
      }

      private int x_ ;
      /**
       * <code>required int32 X = 3;</code>
       */
      public boolean hasX() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 X = 3;</code>
       */
      public int getX() {
        return x_;
      }
      /**
       * <code>required int32 X = 3;</code>
       */
      public Builder setX(int value) {
        bitField0_ |= 0x00000004;
        x_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 X = 3;</code>
       */
      public Builder clearX() {
        bitField0_ = (bitField0_ & ~0x00000004);
        x_ = 0;
        onChanged();
        return this;
      }

      private int arch_ ;
      /**
       * <code>required int32 arch = 4;</code>
       */
      public boolean hasArch() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 arch = 4;</code>
       */
      public int getArch() {
        return arch_;
      }
      /**
       * <code>required int32 arch = 4;</code>
       */
      public Builder setArch(int value) {
        bitField0_ |= 0x00000008;
        arch_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 arch = 4;</code>
       */
      public Builder clearArch() {
        bitField0_ = (bitField0_ & ~0x00000008);
        arch_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:cssort.ProfilerToClientInfo)
    }

    static {
      defaultInstance = new ProfilerToClientInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:cssort.ProfilerToClientInfo)
  }

  public interface ClientToProfilerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cssort.ClientToProfiler)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int64 averageProcessTime = 1;</code>
     */
    boolean hasAverageProcessTime();
    /**
     * <code>required int64 averageProcessTime = 1;</code>
     */
    long getAverageProcessTime();

    /**
     * <code>required int64 averageRequestTime = 2;</code>
     */
    boolean hasAverageRequestTime();
    /**
     * <code>required int64 averageRequestTime = 2;</code>
     */
    long getAverageRequestTime();

    /**
     * <code>required int64 clientRunTime = 3;</code>
     */
    boolean hasClientRunTime();
    /**
     * <code>required int64 clientRunTime = 3;</code>
     */
    long getClientRunTime();
  }
  /**
   * Protobuf type {@code cssort.ClientToProfiler}
   */
  public static final class ClientToProfiler extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:cssort.ClientToProfiler)
      ClientToProfilerOrBuilder {
    // Use ClientToProfiler.newBuilder() to construct.
    private ClientToProfiler(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ClientToProfiler(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ClientToProfiler defaultInstance;
    public static ClientToProfiler getDefaultInstance() {
      return defaultInstance;
    }

    public ClientToProfiler getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ClientToProfiler(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              averageProcessTime_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              averageRequestTime_ = input.readInt64();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              clientRunTime_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cssort.protocol.ProfilerClientProtocol.internal_static_cssort_ClientToProfiler_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cssort.protocol.ProfilerClientProtocol.internal_static_cssort_ClientToProfiler_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cssort.protocol.ProfilerClientProtocol.ClientToProfiler.class, cssort.protocol.ProfilerClientProtocol.ClientToProfiler.Builder.class);
    }

    public static com.google.protobuf.Parser<ClientToProfiler> PARSER =
        new com.google.protobuf.AbstractParser<ClientToProfiler>() {
      public ClientToProfiler parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ClientToProfiler(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ClientToProfiler> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int AVERAGEPROCESSTIME_FIELD_NUMBER = 1;
    private long averageProcessTime_;
    /**
     * <code>required int64 averageProcessTime = 1;</code>
     */
    public boolean hasAverageProcessTime() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 averageProcessTime = 1;</code>
     */
    public long getAverageProcessTime() {
      return averageProcessTime_;
    }

    public static final int AVERAGEREQUESTTIME_FIELD_NUMBER = 2;
    private long averageRequestTime_;
    /**
     * <code>required int64 averageRequestTime = 2;</code>
     */
    public boolean hasAverageRequestTime() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 averageRequestTime = 2;</code>
     */
    public long getAverageRequestTime() {
      return averageRequestTime_;
    }

    public static final int CLIENTRUNTIME_FIELD_NUMBER = 3;
    private long clientRunTime_;
    /**
     * <code>required int64 clientRunTime = 3;</code>
     */
    public boolean hasClientRunTime() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int64 clientRunTime = 3;</code>
     */
    public long getClientRunTime() {
      return clientRunTime_;
    }

    private void initFields() {
      averageProcessTime_ = 0L;
      averageRequestTime_ = 0L;
      clientRunTime_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasAverageProcessTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAverageRequestTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasClientRunTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, averageProcessTime_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, averageRequestTime_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, clientRunTime_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, averageProcessTime_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, averageRequestTime_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, clientRunTime_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static cssort.protocol.ProfilerClientProtocol.ClientToProfiler parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cssort.protocol.ProfilerClientProtocol.ClientToProfiler parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cssort.protocol.ProfilerClientProtocol.ClientToProfiler parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cssort.protocol.ProfilerClientProtocol.ClientToProfiler parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cssort.protocol.ProfilerClientProtocol.ClientToProfiler parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cssort.protocol.ProfilerClientProtocol.ClientToProfiler parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static cssort.protocol.ProfilerClientProtocol.ClientToProfiler parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static cssort.protocol.ProfilerClientProtocol.ClientToProfiler parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static cssort.protocol.ProfilerClientProtocol.ClientToProfiler parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cssort.protocol.ProfilerClientProtocol.ClientToProfiler parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(cssort.protocol.ProfilerClientProtocol.ClientToProfiler prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cssort.ClientToProfiler}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cssort.ClientToProfiler)
        cssort.protocol.ProfilerClientProtocol.ClientToProfilerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cssort.protocol.ProfilerClientProtocol.internal_static_cssort_ClientToProfiler_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cssort.protocol.ProfilerClientProtocol.internal_static_cssort_ClientToProfiler_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cssort.protocol.ProfilerClientProtocol.ClientToProfiler.class, cssort.protocol.ProfilerClientProtocol.ClientToProfiler.Builder.class);
      }

      // Construct using cssort.protocol.ProfilerClientProtocol.ClientToProfiler.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        averageProcessTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        averageRequestTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        clientRunTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cssort.protocol.ProfilerClientProtocol.internal_static_cssort_ClientToProfiler_descriptor;
      }

      public cssort.protocol.ProfilerClientProtocol.ClientToProfiler getDefaultInstanceForType() {
        return cssort.protocol.ProfilerClientProtocol.ClientToProfiler.getDefaultInstance();
      }

      public cssort.protocol.ProfilerClientProtocol.ClientToProfiler build() {
        cssort.protocol.ProfilerClientProtocol.ClientToProfiler result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cssort.protocol.ProfilerClientProtocol.ClientToProfiler buildPartial() {
        cssort.protocol.ProfilerClientProtocol.ClientToProfiler result = new cssort.protocol.ProfilerClientProtocol.ClientToProfiler(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.averageProcessTime_ = averageProcessTime_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.averageRequestTime_ = averageRequestTime_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.clientRunTime_ = clientRunTime_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cssort.protocol.ProfilerClientProtocol.ClientToProfiler) {
          return mergeFrom((cssort.protocol.ProfilerClientProtocol.ClientToProfiler)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cssort.protocol.ProfilerClientProtocol.ClientToProfiler other) {
        if (other == cssort.protocol.ProfilerClientProtocol.ClientToProfiler.getDefaultInstance()) return this;
        if (other.hasAverageProcessTime()) {
          setAverageProcessTime(other.getAverageProcessTime());
        }
        if (other.hasAverageRequestTime()) {
          setAverageRequestTime(other.getAverageRequestTime());
        }
        if (other.hasClientRunTime()) {
          setClientRunTime(other.getClientRunTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasAverageProcessTime()) {
          
          return false;
        }
        if (!hasAverageRequestTime()) {
          
          return false;
        }
        if (!hasClientRunTime()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cssort.protocol.ProfilerClientProtocol.ClientToProfiler parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cssort.protocol.ProfilerClientProtocol.ClientToProfiler) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long averageProcessTime_ ;
      /**
       * <code>required int64 averageProcessTime = 1;</code>
       */
      public boolean hasAverageProcessTime() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 averageProcessTime = 1;</code>
       */
      public long getAverageProcessTime() {
        return averageProcessTime_;
      }
      /**
       * <code>required int64 averageProcessTime = 1;</code>
       */
      public Builder setAverageProcessTime(long value) {
        bitField0_ |= 0x00000001;
        averageProcessTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 averageProcessTime = 1;</code>
       */
      public Builder clearAverageProcessTime() {
        bitField0_ = (bitField0_ & ~0x00000001);
        averageProcessTime_ = 0L;
        onChanged();
        return this;
      }

      private long averageRequestTime_ ;
      /**
       * <code>required int64 averageRequestTime = 2;</code>
       */
      public boolean hasAverageRequestTime() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 averageRequestTime = 2;</code>
       */
      public long getAverageRequestTime() {
        return averageRequestTime_;
      }
      /**
       * <code>required int64 averageRequestTime = 2;</code>
       */
      public Builder setAverageRequestTime(long value) {
        bitField0_ |= 0x00000002;
        averageRequestTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 averageRequestTime = 2;</code>
       */
      public Builder clearAverageRequestTime() {
        bitField0_ = (bitField0_ & ~0x00000002);
        averageRequestTime_ = 0L;
        onChanged();
        return this;
      }

      private long clientRunTime_ ;
      /**
       * <code>required int64 clientRunTime = 3;</code>
       */
      public boolean hasClientRunTime() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int64 clientRunTime = 3;</code>
       */
      public long getClientRunTime() {
        return clientRunTime_;
      }
      /**
       * <code>required int64 clientRunTime = 3;</code>
       */
      public Builder setClientRunTime(long value) {
        bitField0_ |= 0x00000004;
        clientRunTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 clientRunTime = 3;</code>
       */
      public Builder clearClientRunTime() {
        bitField0_ = (bitField0_ & ~0x00000004);
        clientRunTime_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:cssort.ClientToProfiler)
    }

    static {
      defaultInstance = new ClientToProfiler(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:cssort.ClientToProfiler)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cssort_ProfilerToClientInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cssort_ProfilerToClientInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cssort_ClientToProfiler_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cssort_ClientToProfiler_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034ProfilerClientProtocol.proto\022\006cssort\"I" +
      "\n\024ProfilerToClientInfo\022\t\n\001N\030\001 \002(\005\022\r\n\005del" +
      "ta\030\002 \002(\005\022\t\n\001X\030\003 \002(\005\022\014\n\004arch\030\004 \002(\005\"a\n\020Cli" +
      "entToProfiler\022\032\n\022averageProcessTime\030\001 \002(" +
      "\003\022\032\n\022averageRequestTime\030\002 \002(\003\022\025\n\rclientR" +
      "unTime\030\003 \002(\003B)\n\017cssort.protocolB\026Profile" +
      "rClientProtocol"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_cssort_ProfilerToClientInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cssort_ProfilerToClientInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_cssort_ProfilerToClientInfo_descriptor,
        new java.lang.String[] { "N", "Delta", "X", "Arch", });
    internal_static_cssort_ClientToProfiler_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_cssort_ClientToProfiler_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_cssort_ClientToProfiler_descriptor,
        new java.lang.String[] { "AverageProcessTime", "AverageRequestTime", "ClientRunTime", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
